### PR TITLE
feat: Add vulnerability checking.

### PR DESCRIPTION
**Pull request by adam-moss**
Add `snyk` for vulnerability checking and include testing of production dependencies.

Update production dependencies to resolve identified vulnerabilities (**note** some vulnerabilities still exist in the devDependencies).

### CODE REVIEW

**Comment by mike-goodwin** [comment]
Thank you for this! I have tried to add snyk to the build workflow on my [current development branch](https://github.com/mike-goodwin/owasp-threat-dragon/tree/browserify) but unfortunately there was a bug in the snyk cli tool on Windows that prevents it from running. I had a suggestion from the snyk support people on how i might work around it but I haven't had chance to try their suggestion yet. I don't want to accept a PR that will break the workflow on Windows without being able to provide some instructions in the README on how people can get it to work.

Now that you did this, I will focus back on fixing snyk for Windows...

Does that make sense?

**Comment by adam-moss** [comment]
Mike, yes, that makes sense, although personally I'd forego some compatibility in favour of security.  That being said I'm probably a little biased since I don't have to use a Windows machine for non-MS development anymore.

As a suggestion to allow this to move forward, how about I modify this MR so that instead of running `snyk` as part of `npm test` directly, it is a separate script and then update `.travis.yml` to run that individual script as a `before_script` or `after_success`?

That way it shouldn't impact your Windows setup and once the issue with the cli is resolved you can just include that in the `npm test` step?

What do you think?

**Comment by mike-goodwin** [comment]
That would work. I develop on Windows, so obviously it was a bit of a blocker for me :)

**Comment by adam-moss** [comment]
Righto, all done.

As for the code-coverage, I guess there was a problem with the CodeCov service - the build output showed:

    <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>

    <title>Application Error</title>
    </head>

    <body>
      <iframe src="https://d234q63orb21db.cloudfront.net/cd118a714294f80d079e8514f43792f519841d20/media/html/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>

If not sure if you would have preferred that to fail the build or not?

Regards

**Comment by mike-goodwin** [comment]
I saw that this was replacing jade with pug and this triggered me to remember that I'd had some problems moving to pug before so I tried it locally and there were issues. Mainly that bootstrap-jade does not work with pug at all (needs some file renames to fix it). I think I would need to fork it and port it to pug to make it work.

Also, there is a breaking change in specifying attributes as variables.

It's worrying that my test suite does not pick any of this up. I guess I need to put quite a few new tests in :(

Anyway - I'm really sorry to say I can't merge this as is. It's my bad for not have having enough tests.

**Comment by adam-moss** [comment]
Yep, got to replace `jade` because of the vulns in `transformer`.  There is an MR against JADE-Bootstrap that would potentially resolve it, but that has been outstanding since 6th may.  One of the many reasons we try to avoid using templating languages :)

**Comment by mike-goodwin** [comment]
agree on templating. i only put it in so i could do CSRF protection on login/logout. minimal use :(

thinking about forking jade-bootstrap, but what a yak shave

**Comment by adam-moss** [comment]
Yeah, that's more effort than it is worth I reckon.
If you went down the microservice route you could user express.csrf to achieve the same result.  Wouldn't be a fat browser client then though (which from my PoV is a good thing because Citrix).

**Comment by mike-goodwin** [comment]
Update on this: I shaved the yak and[ ported jade-bootstrap to pug](https://github.com/mike-goodwin/pug-bootstrap). I'll try to write some tests, get snyk working on Windows and then (finally) merge this :)

Sorry it's taking so long - I do appreciate your contribution.

**Comment by adam-moss** [comment]
That's a lot of extra work!

**Comment by mike-goodwin** [comment]
Finally, after too many months, I have implemented this through a different PR and merged into master. It is currently set to not fail the build if vulnerabilities are found - because of breaking changes in the JointJS and jQuery versions. I'll change that as soon as I fix the breaking changes. Sorry for the time it's taken and thanks again for the contribution!

**Pull request closed without merging**
