### PR TITLE
JG - Initial rewrite of TD install instructions

### PR DESCRIPTION
**Pull request by jeg1972**
First re-write of TD installation instructions based on me trying to install it for the first time.  Will update as and when I find more things out.

### CODE REVIEW

**Comment by mike-goodwin** [comment]
Thanks John - much appreciated. I have a couple of comments though:

1. Something has gone wrong with the formatting - it looks like it's using blockquotes or something?
2. The `export foo=bar` is for bash only. It won't work for Windahs users

**Comment by jeg1972** [comment]
1. Formatting looks OK to me on the forked version?
https://github.com/jeg1972/owasp-threat-dragon/tree/palindrome-td-dev
2. Will sort out that... I do forget about Windaz users :-)

**Comment by mike-goodwin** [comment]
This is what it looks like for me:

image

Blockquotes?

**Comment by jeg1972** [comment]
Yes, the idea was to use it as a visual distinction rather than block
quotes per second, I can take that out, give me a sec.

**Comment by mike-goodwin** [comment]
Accepted PR#23 instead

**Pull request closed without merging**
